language: java
jdk: openjdk7
cache: apt
env: COVERTOKEN=sxLu9vzCd8vwevxFgnQ0xX/JRLyc3fnrmOiVX8b+anmkhxB3Az8UbChrWdp9u0rRl1bvUTEB5d9BAVhaRB/zBbNISKFRgNWGZdhTAv2UhCAYv3UobcOruZRbgSDO97MNEw2xf9VHfQd/Fnk9UFWXQSxCMrTO0mWJTDLUiljcTgQ=
branches:
  only: master
deploy:
  provider: heroku
  api_key:
    secure: ieVL0OqUlclYQRTg6FzVj84trrqobDQ2a3k2VvJTjl/TPOYtes4FMuJfDBtpfFD+bxBo24kCcqgVuFV9sYWy+Lgh69+iUFFTkz1YI3xrKox6Dh0jztx1flmcsPc5ogfCgt4JtoGzII9IUGqzgLLoyU7pVqAlt8M4hoHgw9TXIxU=
  app: 
    master: staging-tictaceax
    production: tictaceax
  on:
    repo: teameax/tictaceax
after_script:
  - "export STAGING_SERVER=http://staging-tictaceax.herokuapp.com/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "sh bin/selenium_test_xvfb"
after_success:
  - mvn test jacoco:report coveralls:jacoco
  - git push heroku master
notifications:
  email:
    recipients:
      - aevar12@ru.is
      - sigursteinn11@ru.is
      - jonaj11@ru.is
      - aria12@ru.is
      - arnarhk10@ru.is
      - marteinnt10@ru.is
    on_success: change
    on_failuer: always